### PR TITLE
Update paradigms.ipynb

### PR DESCRIPTION
**Pull request by simranwaqar27**

### CODE REVIEW

**Comment by klieret** [comment]
Thanks, that's a bit more verbose. But I will wait with merging this until after iCSC, since it's no bug

**Comment by simranwaqar27** [comment]
ok, thank you for your response.
Do tell me i am doing it in a right way or not.

**Comment by klieret** [comment]
Hi @simranwaqar27 I'm a bit confused. Opening a pull request means that you want to change something in this repository, right (I was assuming you didn't like the example to be slightly different from that of the lecture)? 

The solutions in this file are given for you to check your solution or in case you didn't come up with a solution.
We are not checking your solutions personally.
However, consultation time is provided on Thursday, so please join if you want to discuss.

**Comment by simranwaqar27** [comment]
No it does not like that.
Firstly i don't understand how to solve and make changes in that code and
create a pull request.
Later i get to know that jupyter notebook is used for that purpose.
I'll definitely practice it and do code according to my own understanding.
Once i ll do it then i ll save the code in jupyter.  Hope you got me.

Regards:
Simran Waqar

**Pull request closed without merging**
